#! /bin/bash 
#
#SBATCH --job-name=real
#SBATCH --output=real_output.txt
#SBATCH --partition=hicpu
#SBATCH --ntasks=40
#SBATCH --mem=40000
#
#=======================================================================
#
# real
#
#=======================================================================

########################################################################

if [ "$PROMETEO_ROOT" == "" ]
then
  echo "PROMETEO_ROOT not defined!"
  exit -1
fi

if [ "$WRF_ROOT" == "" ]
then
  echo "WRF_ROOT not defined!"
  exit -1
fi

if [ "$WRF_VERSION" == "" ]
then
  echo "WRF_VERSION not defined!"
  exit -1
fi

if [ "$WRF_COMPILER_VERSION" == "" ]
then
  echo "WRF_COMPILER_VERSION not defined!"
  exit -1
fi

# Set the software environment
export WRF=${WRF_VERSION}-${WRF_COMPILER_VERSION}
echo "${HOSTNAME}: $0 $WRF_ROOT $WRF"
echo "Sourcing $WRF_ROOT/ext/sourceme-$WRF_COMPILER_VERSION"
. $WRF_ROOT/ext/sourceme-$WRF_COMPILER_VERSION
########################################################################

jobId=$1
THISDIR=`pwd`

namelistInput=$2
cp $namelistInput .

metgridResults=$3
cp $metgridResults .

# Soft link to executable and data
ln -s $WRF_ROOT/$WRF/WRFV3/run/real.exe 

# Run
time mpirun $THISDIR/real.exe
